-- Create workout_plans table
CREATE TABLE IF NOT EXISTS workout_plans (
  id TEXT PRIMARY KEY,
  member_id TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  goal TEXT NOT NULL CHECK (goal IN ('strength', 'endurance', 'weight_loss', 'muscle_gain', 'general_fitness', 'flexibility', 'athletic_performance')),
  duration INTEGER NOT NULL,
  frequency INTEGER NOT NULL,
  difficulty TEXT NOT NULL CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  start_date DATE NOT NULL,
  end_date DATE,
  created_by TEXT DEFAULT 'ai'
);

-- Create workouts table
CREATE TABLE IF NOT EXISTS workouts (
  id TEXT PRIMARY KEY,
  workout_plan_id TEXT NOT NULL REFERENCES workout_plans(id) ON DELETE CASCADE,
  member_id TEXT NOT NULL,
  name TEXT NOT NULL,
  date DATE NOT NULL,
  exercises JSONB NOT NULL DEFAULT '[]',
  duration INTEGER,
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'in_progress', 'completed', 'skipped')),
  notes TEXT,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  completed_at TIMESTAMPTZ,
  warmup JSONB,
  week_number INTEGER,
  session_type TEXT CHECK (session_type IN ('strength', 'hypertrophy', 'conditioning', 'power', 'deload')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_workout_plans_member_id ON workout_plans(member_id);
CREATE INDEX IF NOT EXISTS idx_workout_plans_status ON workout_plans(status);
CREATE INDEX IF NOT EXISTS idx_workouts_plan_id ON workouts(workout_plan_id);
CREATE INDEX IF NOT EXISTS idx_workouts_member_id ON workouts(member_id);
CREATE INDEX IF NOT EXISTS idx_workouts_date ON workouts(date);
CREATE INDEX IF NOT EXISTS idx_workouts_status ON workouts(status);

-- Add comments
COMMENT ON TABLE workout_plans IS 'Stores workout plans generated by AI or created by trainers';
COMMENT ON TABLE workouts IS 'Individual workout sessions linked to workout plans';
COMMENT ON COLUMN workouts.exercises IS 'Array of exercise objects with sets, reps, weight, etc.';
COMMENT ON COLUMN workouts.warmup IS 'Warmup protocol with general, mobility, and ramp sets';
